version: "3.1"
volumes:
  postgres_storage:
  minio_storage:
  strapi_storage:

services:
  strapi:
    build:
      context: ../arcade-strapi
      args:
        - STRAPI_NODE_ENV=${STRAPI_NODE_ENV}
        - STRAPI_APP_KEYS=${STRAPI_APP_KEYS}
        - STRAPI_API_TOKEN_SALT=${STRAPI_API_TOKEN_SALT}
        - STRAPI_ADMIN_JWT_SECRET=${STRAPI_ADMIN_JWT_SECRET}
        - STRAPI_TRANSFER_TOKEN_SALT=${STRAPI_TRANSFER_TOKEN_SALT}
        - STRAPI_JWT_SECRET=${STRAPI_JWT_SECRET}
        - DATABASE_CLIENT=${DATABASE_CLIENT}
        - DATABASE_HOST=${DATABASE_HOST}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_SSL=${DATABASE_SSL}

    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - STRAPI_NODE_ENV=${STRAPI_NODE_ENV}
      - STRAPI_APP_KEYS=${STRAPI_APP_KEYS}
      - STRAPI_API_TOKEN_SALT=${STRAPI_API_TOKEN_SALT}
      - STRAPI_ADMIN_JWT_SECRET=${STRAPI_ADMIN_JWT_SECRET}
      - STRAPI_TRANSFER_TOKEN_SALT=${STRAPI_TRANSFER_TOKEN_SALT}
      - STRAPI_JWT_SECRET=${STRAPI_JWT_SECRET}
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}

    volumes:
      - ../arcade-strapi/config:/opt/app/config
      - ../arcade-strapi/src:/opt/app/src
      - ../arcade-strapi/package.json:/opt/package.json
      - ../arcade-strapi/yarn.lock:/opt/yarn.lock
      - ../arcade-strapi/.env:/opt/app/.env
      - ../arcade-strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"

  postgres:
    image: postgres:16.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_storage:/var/lib/postgresql

  redis:
    image: redis:7.2-alpine
